### ISSUE TITLE
Automatic page correction

### ISSUE THREAD

**Issue by BioExorzist** [holtwick/pdfify#65] opened 2021-01-06 15:12 UTC
Please explain your idea to make the app better:
That the scanner detects if a document has been scanned the wrong way and then automatically rotates the page correctly. Possibly also with minimal rotations of 1-2 percent.

App Version Info:
de.holtwick.mac.PDFify@3.3.2+130 0ABA9TA42H6NK6BPKVTZDX8Y9R

**Comment by holtwick** [comment] 2021-10-15 15:26
See also #28

**Comment by holtwick** [comment] 2022-03-08 09:48
Duplicate of https://github.com/holtwick/pdfify/issues/28

**Closed by holtwick** 2022-03-08 09:48 UTC
Labels: enhancement
