### ISSUE TITLE
macOS right-click shortcut to OCR a PDF without going into the app?

### ISSUE THREAD

**Issue by rlgn** [holtwick/pdfify#74] opened 2021-12-26 04:49 UTC
Love the app, this has been an app I've been looking for the past 2 years for the Mac.

Do you guys have plans to make some sort of shortcut for macOS where I can right click a file, click "OCR this document" which creates a new searchable PDF in the directory that I'm in?

Great job on this!

App Version Info:
de.holtwick.mac.PDFify@3.3.2+130 BJ5JKPT1WX5355PSEDQB55G8XG

**Comment by holtwick** [comment] 2022-03-08 09:24
Yes this is on the list.

**Comment by holtwick** [comment] 2022-03-08 09:27
Duplicate of https://github.com/holtwick/pdfify/issues/71

**Closed by holtwick** 2022-03-08 09:27 UTC
Labels: enhancement

**Comment by mat1696** [comment] 2022-03-20 16:55
Do you have an ETA for this ?

**Comment by holtwick** [comment] 2022-03-22 08:42
It is possible in the latest beta, although only for PDF files and still in development. Get it via https://pdfify.app/en/help#beta
 
![20220322-093932-capture-holtwick@2x](https://user-images.githubusercontent.com/49557/159441214-f196ccf9-096f-44c7-866f-341a6f35f78a.png)
